name: expenses_tracker_ddd
description: Expenses Tracker DDD
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  #  State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #  Service Locator
  get_it: ^7.6.4

  #  Helpers
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1

  #  Logging
  logger: ^2.0.2+1

  #  UI
  shimmer: ^3.0.0
  flutter_hooks: ^0.20.3
  device_preview: ^1.1.0
  fl_chart: ^0.65.0

  #  Local DB
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  wolt_modal_sheet: ^0.2.0

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
  generate: true
